
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    username: root
    password: Zxy20010202
    url: jdbc:mysql://localhost:3306/workingman?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  type-aliases-package: com.workingman.javaBean
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 8083
debug: true

